apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chromadb-pvc
  labels: 
      app: "chroma-db"
spec:
  accessModes:
    - ReadWriteOnce
  #volumeName : mongodb-pv
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 2Gi 